//
// Created by Samuel Barnes on 11/10/24.
//

#include "Day1.h"
#include <string>

int Day1::Part1() {
    const std::string input{
        "CCAAACACAACCAABAACABACBCCBBABBCAABCACBCBCCABAAACBBBCCACCBAACABBBBCBAAAACABACACBACACCCACACABABACCCCAABBABABBCCCBCBCBBCBBCACBBBAACCCBACBAABACABACAAACABCBCBCBCBCCBBAABBABAAABCCAABBCCABCACCCBBBCCAABBBCACACAACABCCACBBBBBCCCABBACCBAACABCAACCCCABBBCCCBCBBBCABACCCCCCACBBBCBACABCABBBCCBBBCCABACCBCCBBAABABBCCBCBABCCCAACAACCBBCCCACACAACAAABABBCBAABABCCCABABCAABABBBCBCCAAABABCAACAABBACCBCBABAABCAAABBBACBCACAACCBAACACABCBABABBAAACBAACCCCBCABAACBBABCBCABCAABABABACBAABCCABCABBCBCABBBBBABBBBAAABBACBAACBCABCCBCBACCBABBCBACCABAAAABCAACAABCABAABCCCAAABBAAABAACCAACCBBCBCBAAAAAABBAAABABBCCCBAACCABACCCBBBBBCBABCACCACBBACBBBBCABBCCCAACBACBAAABACACCABBCBCBACABBCACBABAAAACCCBAACACACBCCBBBAACCAACBBACCCBABACAACBCABBBACBBBBCCBCCBBCBBBBAACAACBBCCCBABBABBBBCAACBBACBACCACAAACCCBBCCABBCABCCBBBCAABBACBCBBAABCACBCBABCBBBACBAAAACBABCBABAACABCCABCBBAABCAACCCCABCBBBCCCBBBCABBBABBCACACCCCCBABCABBCCCAABACBCAAACCCCBBAACABBAACCBBCBBBABBBBAABCBCACABACBACBBBBACACCAACAABACBBBAACCBABBBBABBBBAAACBAAAAABBCCCACCACAACBAABBCAAABCCCCCB"
    };

    int total = 0;
    int a = 0;
    int b = 1;
    int c = 3;

    int length = input.length();

    for (int i = 0; i < length; i++) {
        char current = input[i];
        switch (current) {
            case 'B':
                total += b;
                break;
            case 'C':
                total += c;
                break;
            default:
                total += a;
        }
    }
    return total;
}

int Day1::Part2() {
    const std::string input{
        "ABxDDDACACDADABCCADxABBDBACADDDBCCDBBBDBBABCDCADADBABAAADACAxDACCABBxCxDDCBDBCDBDxBCDBBDBCxCDCDBBBxxBDCABADDAADCBDCDADCDDBDCCxCCADADDADxDDDCDxDACCCCADCCxADBxxDCDDBBBBCABDCCBACCCxDCDACBCDCBAxBBADACDCBDxCABCCDxBxCDCABCBADxCCDDCxCBDABCACBDxDADxAxACBABCCDCxDDBBBABCABCADDCBCDADDBADBBCxBCCDCBBCCAADDCBCDBAAABxBCCCxxDDADCBACACCBBCCCDCBBCDBDACxBDBBxDCCAACDBDACDBBxxBDCxDBCACACDABBBDDDxxBDxDACBAABCBACBDDBBBxDCDBBABDAACCCDDDABAACACxDCBAAABxDBAxBAAABDxADxBABBDADBCADBAACCBBBABxCxDCADDxCADDACDCABBCAADBBDCCACADDBDACACBADABAxCBAAABDBBACBACDCAADDDBDACCBxBxBCDDADCCCADAxBADDxACDDxxxDACxCBAAxCDBDDABCCBDABxABAACBDDCAADDCCAABDBAABxCABDBCCACBBADBDBAAADBDBCBDDBDDxADxDBBxBCBABCACACACABxCBBBBxCAAABCBDDDBBDCCxBCxABCBDCACDAADABDBBABACCDAxAxAACDxCDDAAxAAABCACAABDDCxDBADCCCBACxxxACBBBDACDACDxADAAAAACADDBDADCDCxxCBBAADxCDDDCCCDDxxDACAACDDDCDACxAxDCxCADADCCACDxDBBCACDxDCBCAAxBAABCBBxADDDCADDBADDAACBDCDADBDDCDBADCDBCACCBxBDAAABxCDBDCAAAAxDDCCDDBCCADABAABxCDBDxDCCCCBCCDCBxADABCxACDAxDCDxADBAACxACDxCADxBBBBCDCCABADxBCABBBBxBADADxADDAAAACBADxDBxxACBDxBDAxCCCCACxBDDDCBDxCCACCCAABBBCACxCxDDxDDxADAADBABABAxxCCCAAACCCDABABADCBBxxCBBADABxxCxDDBBxAxCCBAACABxAABxBAAADDxDDBDCDDCBCDCCCxDCCCAxAxACAADDACBBxBBCBxADDBDBAABBDBBDDDCBCCBABAABABDCAxADAxCDBBCADBxBABDDBCBxDDABADDCBDBCBDxBDDBxADDDCxBCDADxxDDDCCCDCBDCDADDDBADCDDCBxDBDxCBxAACBCBDBCDBCDDBCxACDBABAxAABABDADxBACDADBBDACCDADDBBBCCABDCDCDABADAxCDAxBBDCACACDBCCDCDABDAADCCDBCCCDCABABxCCDACBBxCxCDBBCBCDCBDDDADCxBABxCABDxBCxBxACDxAAAAxxABAAxCCAxCBDABxBBxxCCBCCxAACBCACBDxxADABCDCCCCCBBAxCDDDBCDDDCDACADDADBBCBDCAAADDxBCCCDABAxDCBBBCADCDBCBAADBBADBDDCDACCABBxADxDBACACBCCADDCBACCCCBCBBACBDDCAADCCBCBCAACAxBBCBACABABDCAADBxCDBDCADCCDABACDxBADACACxDDDCBCBBDCAxCBACCCBBDCBCDxBDAABDDCDCDBBBBACBCDAxDDAAACABACDACBBCDDDAABxCCBBCABCABCxDACCBBDACDDDxABDBACBDBADDBBBDAxAAABBxCBDBCAxDCBCCABCCBBCDxCCABBCBACABCCxCCCxADBDBDCACBDxBACDADBDCCBDDCCCxCCCCDDDDDBCCDBCBDCxDACAACxADCDDACCDDCBACCDDACACAACCDBABBBCCAAxDADxxACBAABAABCDABAxDCDABCCCCCBDDCxxBCBBxDDADBCCDCACBACDACCADDAxxBCDDDBDCCADxCCAx"
    };
    int total = 0;
    int a = 0;
    int b = 1;
    int c = 3;
    int d = 5;

    int length = input.length();

    for (int i = 0; i < length; i += 2) {
        char enemy1 = input[i];
        char enemy2 = input[i + 1];

        if (enemy1 != 'x' && enemy2 != 'x') {
            total += 2;
        }

        switch (enemy2) {
            case 'B':
                total += b;
                break;
            case 'C':
                total += c;
                break;
            case 'D':
                total += d;
                break;
            default:
                total += a;
        }
        switch (enemy1) {
            case 'B':
                total += b;
                break;
            case 'C':
                total += c;
                break;
            case 'D':
                total += d;
                break;
            default:
                total += a;
        }
    }

    return total;
}

int Day1::Part3() {
    const std::string input{
        "CCAxDAxBBDBAAAABDBCCxAxCxBxBDDDABDADBAADAABAADADDABBxCACDACxDAAxDBxDCCAACCCxxDxCCDBDxxxCDAxDBDCBxxBDDBDxDABBCxBCDDCDADxxCCBACCBDDBCAABCCBDCCxAxABxDxBBCBDABDBBDABxDDABDCxxxACABBxCBACABxAAxACDBxACBDBACxDCBAAACBBCxDAxDCAABxxBACBDBCxAAADDxxDDBCABBCBACDDBBxCxBxACxxADBAADCCxCBBCDxCCACxxDDxCDDCCABCDABDABDABABBBACDDCxDDDDDxxBBDAxBBxDBDBBxCDxDADDxxDxBCBDBDBCBBACCCxDCDABCBDBACDACAAADDDCCBCxxBADCxDBBCCxxxBBxBCxxDCxDCCCDxxDACDCAABCBxACADCxDDDDxBBCACBDxCBCxDxxBAAAxxCxxxBDxDCDxDBxCxxAABBxABCBBACCDCDADxDACDBBBDCCxADDBADxBCxxAADACAAxCBCDBCxCDBBAAxCAACCxCDAABAAxxxxAADCCDxCxCxAABDABCDBACBDCDxxxABCBxCDDADAACCABAxCADADxAxDDDBDAxAxxCACDDADDCDABDAxCBxCAACxCBxxAACDCCxCCDAxDACCAAADCBDDAxxBBDCxAxxDDCBBDBxDCBDCAAxBCxBAxDCADBAACxCBDCxAABCxAADBDDCDCACCBBDCBxAAxDABxDACxAAxxADDCBBDAABCxADxAxBAAAxADCDCCDABACDDCxDBCACBDCDCCxxCxCCxCBDCDCxABADBADDBBxCCBCACABxABxCBBAABCAABCBDDADADDCBDAADCABDCDCBCCCCBCDCxADCCxAxxCBxxxxxCCABBDAACDBBxDBCDxxCxBBxDDCBxBADBBxCCAADxDCCDxCDDxCBBCDCCBAxDCxBxxCxABAACCBBAxBDxxBCBADCCBBAxxDAxCxxCDBxDxBxCACxAxCDDADCBBDACADAAABxBDDxDBAxAxxCCCCBxDDAxBCxBBBACBxCCDCDCAxCDABAAxBABBBABxADDACABDBBDAxCCCxDCAAADxxCxCBxADAADxDBAxDDDCAxCBCCDxDxABAxCDDDCCACBDCxCCxBDDCDACDBAABDADAxDBACBxDCxDCBABBxAxxBCBBDAxxBxxBCBxxxxBDADxAAAABCDDxxCxDCACDDCxADDCDBxCDDBBxCDDDCAxBAxADACDDAABxxxxxBDDxxAxACACxxxBDDCAxBABBDDBAxBAxABCDABACAxxCDCCDxCxBAxBxACDBCBDCCCDDCDDCAxxDAADxCAxBBCBDBxDxxDDxACCxBADBABBBBBBxxDACCxBACCACAxDBADDCDCDCCxABCDDxDxDCxDxAABADCxBxCAxCxCCACAABAxBBACCxxDBCxBxACADDDADCCxCAxADAxBxBDxxDxAxACBxBCxAAABAADAxDxDCxxDBADBAADCBDxBxBDAxxCBABxDxxBAxAABCCxDBABBABxDADBDxBDAAACBxDABxDDDAxxBBBCCCDCDCCDDAxCxCBBCxxxxCCCACADxACBBACBAADCxxxAxACCxABxxADADDCDCBDBxBABDAxDDxADCxxACCDAAAxBDADBBCAABAxBxABxCCADCCAADABxAxxABCBxCABxCBADCACDDBxADxCDBBDxAxBDBCDABBDBxDxCBAAAxAxCABCBCDDCDxxBAxDCADDBACxBDBACCxDBABABAADxDCDDxDAACCAACCDCCDCBxxxACxAAxACxCADBCAABCAACDxCCxBBAxxCxDxCxCAxACCCxAAxxCABxABADAxxACDDCABABDxCBABBDAxDDxDAxDxAADDAADBBDxDABxDxDDCDBCADBxAxDDAxAABCBAxBBBCBCCCDBBCACBCBDACxADxDDDDABxBDAADADCACDxxCCADBDBBADxADDxCDAADDBBBBxxAABDBxDCACBxCCCBBCxCDCACABBDCABACAACDCBAxxABBADBxAxDCABABxACCCDxAxBBxxABBCCDDxAxDCxDACBDCCCBCxADxBxAxBDxxABxADDAxADBxBDDCDBDxxDADABxBxABDBCCxBDDAxDxDCAxAACDADBCACCxABBDABDCCDDACxxCCxDCxABDDCBxDxCAxBCBCAxBxxDABABCxDCxxxCBBAABDxDACxBAxCADABBDBACADCxDxCCBDxCxABDACDBDDxCADABAAxAxxBCBAxCCADCxACCDAADAAAxxxCDBDDDBCCxAxxACDCxDAxAAABxCxADBCAxCAADDCDACBDDACCCDBxxDCBBxDCDxDDABCDDBAACCBBBBxxDxDDDBDBBxBDAxBAADDDxCxxxBDxAxCBBAxBCBxDxDBAxABxBBACDxBBCxBxxDxCxxBDCDBCAABDACxBCBDABBCACACCxBCxBxDCADDxCAxDDABAADBxBCBCAxBDACxCAxCDxxDCCBDDxBABBBCDxBAACBCxxxCxBxADxxADAxAAxAADDABCDAADxAxBDDxxBDBBACDCCDDADCxBCBxADDDACBxCADDDDBDAxCABAxCDCBxADBBCABxBCAxxBxDxBBCACxADAAxDxAxADxCBAAxCxCCBAACBCAxxxDDxADAABCDABCABxADBxAAxACCCCBDABBCxCCBABCxDABDBACCBDBABBxABAxCCBCxxBACxBCxBxxDxCDBxABCBBAABADBxBCxCCCCACCCBBACDxCCBAxBBBxDDAABCxCDBxBCxCBxCDADDBxCxxxDDBDCBDxBADCxCDDxDCxxCxxxCADxxCCDxCCxxCAAABxDDBxADBxxCDBBDBxDAxADCCBCBCDABDADADDBBAxxDBxDAxDDDBxBCBDxCAABACDxCDBxBCADBDxAADCCDBCxxDxCCxDBAABBCCDADBDxCDADDDDADAxxDxBxDBADACAxAxCBDCBxCBxBDCACCCACBxCCCxDCAxBxADDBCDDxCCCBDBAACBBCDADxxABxBBDCxAxADCxCCxCBDBCCDDxDCxxBACDBDxBBADBCBxAxDACBBCDADCxAABxDACCxABDDDACxxxBBDxCCDAABCCxDxDDCDxBCDBDxAACBCDCBABxDDCCCDxDxxBBxxAxDAxCxBCBCxACxCDDCABxADADCxxDACBxBxxCCABBxBxxDBCAxCDBDABCABBDxAAAADAAAxCBCBBDxDCAACCCBxCBAxBCBBxADxDAxACBDDCxDCBBAxCBBCADCCDABxCACxDAxCCxxAxCBCABCADABBxAADCxxACxDBAABDBDDxBxBCxBDBDAACAxDADBDCCAAxADAADBDCABCBxxDAAAACDAABADACBxDDABDBACAxDCBCBAxCxCCAxDAABxxAxBBCxCAABBABCDCxBBxDBDDxACBAAxBCBCACABBDDCCAABCABAACACCBBCCDBBDBACCCABABDBBCBxxBAABBCBxAxxABACxDDDxxDCCDxxCDBBBxDCxxCBBxxDxCxDCxBABADDBBBxAxBACBCDDxADABxDDxBACBBCABCCAxxBxCCxDBBBxxAAxxxCCCBxBBAABCDBDBDDDBxCBAxBAABBBDDxxADDDAxDDADABDDCDBBBAxxBxCAxDxDCBBCCBDADCCCDBxDDADxCACxDxxADACCAADBCDCDADDxABADDCDCCxCBBxxCBBxxDDAxDBxxxBACDxxABDDBxDxDABABDCxxxBxxCCxACxABDDCACDABACADADBBxxxBADCCBACxBDCBCCxAABBDDBDBCCxxABCCxDBBAxxDDADCBCDBDBxDBCxDBxBAxCCDxACBDCDCxDCxCDCCCCxDCADxDAxACDCBBCDDABBAAxAADxCxCCACDBABDAACCDACAABCAABDBCAxDABCADBBDDDDxBxDxDCDCADDBDCxAAxAxCCxDDDBxxBCBBxBBxDADBDCxADAAxDCDxDxDxxxCACDCCCDACxxBDxxDAxxxCCAADCxACAABDBDABAAxBxBCAABxxCCCBxAABDBACxCACAxBAxCCAxCACCxACCABDxCADxCxBDxCDDBBACBBxBBDDCCCBDAAxxxDDDABxBBBxAACDDBDDDADxDAACDBDCCDCBBDCACABCDBADxABDxCAAxDDDAAxDCBxDBBxxABDBCACACCBxBBxDDxBABADACCDBCxxDAxBAAACCDAxDxxDBxBBBBCxAxABCDBBxCCxAAAADxABCxDBBDBxCxxACAxADAAxBxCDCADBxCCBDABCBxCxAxCDCCxCBDABAABCABBADDCACAxDDCxxACCxxBCACxDCCAxxDBDxDxADxABxADDBAxxACBBDABABBBACAxAADADxBxBxDDCBACxxBCBADADCDCAxBADxCCCBBBAAADAAxAxACxABxxBADxxBDBDDABBABxAAxDCADCCCCAxCxABxxCDABDCDAACADxCBCCxxxxxDAAxCxBDCBxDAxDxxDDCxCBDBDDxDDCACDxxACxCACCDBABxDBBADACBADABBAABBBDCCCBCxDDCDDBxCAxDACBBDABABDAxAxxCABxCBCDBDBDDACxBDBACCxAABDxBBCxCAxxAAABCBCDDACBCDDDBABABAAACADDDADxxDxBADxDCxABBxAACxxDBDAxCxDABCDBxCAADCACxADBCDxBxCDxBxDBDxxDxAABCDCBDACBDxCBBAACAADABBABDCACxDADxBADBABDBDDCDBADCBCADxCDDAxBxxCxxCBABDBDDBxBBBCBxCxADBxxDxABCDDBDBCxDADDBxDBBAxxAxDDAAAABDDxDxBCDBDAxBxABAxDDBDACxBDBCDAxDCCCAxDDDADAxxCBCCDxxCDAxACxABBAACBCBBACxxDCAAxCBABxAABDxAAxxAABCACCDABAABBDCCxxADDCDBCxBBCCDDxAADBCAADCCxxCDADDCBxBBBxDCCDBACDBDADAAAxxDDxAADBxCxxxDDxABAAxCBBDDAxxBDxDxBADCCDBACDBDBDxDACBxxDAABDADDBDAACBxACAABxBCDxAxBxABDxxxDCCxABCxBxBABBDAxBBCxADAxABxxxCAxBCxADCCDCBBDxBBABBBBxAAAxBCAxCBxxACCCBxBxxABDCDCCBBDCCCDDxxBCACABAAxxCAAABxDCCBxCCCxBBCBABABADADDCADBBBDCBADDBBBACBBxDxDCxCxAAxCxBCBDBADBAADCCxAAAAAADBxAxxxDBCDADxxDxDxCADCDDDACDCDBBBDBCBCCxCAAABAACACCxCDDDDACABBxCxxxxxxBDxDBDDxDCCDxDxxxBBCBACxxDADCBCxAADCAADDDCxxxxCxBxDAACxCCACxxDBDCxxCCAADAxCDBADDABADCAAAxDAxxCACCAxBxDDACBBADCAAxCCDCACCDBDBDBBBCCBCCCxCBCBxxDCCACABDxAAACDACCCDDCxBCBCBxAxDDDACxxBDDBAxADxCACxCCxxDADAAxDDAACAxDCxxABBDxACxCADADBADBCABBDDCCDBADxCBCDxBCABAADBCCAxxADBCBBBBADDxCAACABxADACAxBCAxCxxBDCxxBxDCDBDACCCABDxDDCBADCCADxxDBxDxBADDCDDBBxCDDBDBABBxxBBCDCBAxxBAxCxCCDADAAAAxxBCBxBCxDxDAxxBADDBBBADCADBxBACxxCCBAxCCDxABxDxDBxxCxCxBABDCxBBDCxxxCxCxCCAxAxxABxCCxAAxBxBBAAxAxDBxAxBDDxBDCABAxDCADABxCBABCCDCBxAxDxxAxCABAAACBCCBACBCCBBADACCCxDABCCADDBDBxCCADCCBDxADBCABDxCBBBCDCxBBxxACxBADAxxDCDAxCDDBDxCACBAxBDxAxBBAxBxxCCxDxCDCDDxxAADDAACAxBxABAACCBxxDxBBDxCBDBACBBBCCBDBDDCxDAxADABDxBCBBCCBxBAABxxAxDBxCAxBACxBBxxxxxCAAxxCxDDDCCAACCCBBADACCDxBACCBDxACDDDBBADCCxABDACABABxBBDCDAxxADxDxBCBBCxAxCBABACxxDDBDCCBxxBCDDACCxxCDCABDCABBxACACCCADDCADxADAAAxBBBCDDABBBxCCCADABxBCCAADACCDBDBxCBCBxBBxDCCBDBBDACBBCxBBCxCCCxBCDDxxxABADxCBABCDABDBAADxBxABxCDBAxDAABABDAAAxAxADDCAAABDDxABADCBBDCxBACDBBADBBxCxBDDCADBDDAAxDBDAxABDBAAAxxACBCCBDBBCxAxxDxxCACxADACCxDADBBxCxACCCDxCABBCDBCCADCDACAABAAADCCxDADCCxADDCxxBxDADADAAABxADCAxDAAxDDAADxxACxDBBCBDDxAxDBxCACADxDCAxDACDxCxADDxCBCABDBCBxCBCAxxACDBAxCCBAxCxBDABxABxCBCxCCABAxCxBCDBxBCxBBxDCBxDADDBCDCxDxBxDBDxCxADDACxBCCDxDDxDxCxxCBCDABDxxxDCBDAxDAxDxABxBCAABxBxxCACDBCDBBCCxxxDxAABBDBABxxBBDDBDCDCBBBDADBDBCCCDCADxDDCACCCBBDDBxBDBACxDBDxCCBCDABCAADACDAAAAxxDCxADxAACACCDCDBDBDxDDBCDDAAxDCxDCDDDxDBDCCDBxDBADAxxDBDAxBCxCBAxBxCBxCDCBCBBBAAxAxDCADCxxxxBBxDxDACCDBxDxCAxCBCxADxxDxxxCAxxBDxDBDxAxABBADxADCDAAAxBCxxBxDxABxBBDBDABBACCAABDAADCBCBxDBxxDDDDBxCADDACDAADxCxCxBABBDCBAACBBCCCACCCDBAAxBAAAxACDAxxADAADBDxABDDBDDAxxDxDDBxACCCCBDAACCCAABABDBCAxCBxDxCBCCBCDxBDDBBxxBDBCACDAxAxxBACACCxxACxADBCxxxCCxDDCCCCBAACDADABDCxAAxCCAADDxAADDxDDADxCCABCABAxBxxCCAAxCDAADCxDBDDCxABxBCDCxBBDDBDCBBxBAABCCxCxxDAxBABDDDxDBxCBACxACDAACxCBBADBBxBxxBCxCBABAABxCAACCCxDBCxDBAAxBBCDDxDBBBxBBACDCxAxCxAxxxxCBCDABACCACADDCACBADCCCDBBDxxxADBBCBACBBxACDDABBxDDBCDCABxxDABxCCAAxxCBDADDCADxxBADDCxAABDCBADDCBACBxCCCCCDDAACCCCDADxDDBDCxACDxAADDxBDAxAxAxBDDCDCDDDBDDxBxABCCxxDCDBBCBAxCBBDDxBABDCCBCxCCxxDACCCBAxxABDDxCxxBxABADDDADCBCxxDADDAxDxACBDBBCCADAADAxBBxBBxxCACDCxCDxBCxxBCBBCDCBCCACAxDBCxBADCAAxADxBBAxDDBDCCBABxDBCABBBADDxAAxCADDCBDxCBCDBCBADBADAACCAxBxBAACCADDCCAACBxxDDBAACCBBxDxDCDAxCADxCCDDABDCCxxABADBDADAxADBBAxxDADABCDCAACBBBxCDxCBBxxBBxDDxCxxDCCBCCACADCABABDxDxADABCDBCCBxCBCBDDDAAxCDxCCAxCDxBxBDxxACAxCxxxxCDBxxCxBDxCCxxCBBxBDACxDDCDDABBCDCAABCDADBACCAADDDxAxBBxxBDxDxCxDBBBCxAAACBAxAACCxBCCBCCCBDBCCCxCCCBBABBxxDxAxDxxDxCxAxDxDxDCxxxACDCDBCADDCACDxADBACDCxDDDABDDBxBxDDAxBxDCAxxABxBDBBBAxDAAACDBBBACABDxDACCDDxxxCAxDBxCDBxxDxAACACCCxxxBDBCCxABCBBDxDCBCxCDCBxDBACBABBBxAAxACCACxAADCxCxCBAACDCBBDDACxxDxAACACADBDCAxBADAxCCBBBBxCCAABCDBCBCBCACBBxABACCBABCACxDDDCCBxDDACxAADCBCCCDCxxDBBxAxDBxADCABACAxAADCCDDAxDAACCDDADxCCBCxCDABCCABDCCBCxxCDDxDxBCDBCDAxCxAADCBCBxxCDCBCBDDBCxDBxBxAAxADDCBCxCxDCBABDDxADBxCxDCCCCDCDxABDACxxDADDxBADADxACCxBxDCABxDBDAxxBDxBBAxDBxBCDDBxDxADCBCDCBABAACBDCABCBBADAxAxCABBBAxCBACCCDAAxADCBxxDCxCABCBBDACBxCDCDCxACCDCBCxxxBxCAxABAAAxCxBBCBBAxDBAAxxxAxxDBxxxBDCDBDCDDCDAxBDxCABDxADCCDDABxAABBBDCADBADDCxBDBCBDDAxCCAxDDBxDDxDDDCCCCBCBAxACxAABDADAAAxxCBCCxABBADCDABAxxCADxDBxBDDBxDDCCBBADxABAADDBACDxDACDAACDAxBCDxDAACAACABBxAxBAxxBDBCxDAxBAABBCDxBxAAxCAABDACAxAxDDACDxDDCBAxxDAxDAABCAADBDACBxxBCxBAAADDxBBAABDAAAxBCCABAxADDCAABDABDDDBBCBxBAADADCBxDDDDCBxADxCABCBAxBBxxCCACCxABCxADxAACCAxADAxxAxDBCAxDABCDBCBBCDCBxxABBCDACAACDCBDCDxCADCABABxDCACBCADBCCxxxBxDCDBACxBDBxxABACxxCAAAACBxAACxxDxxAACxDDBACDABxxxDDDBBBAxCADBABCxDxDBDCBxABBDCCxBBDxxBBxCBCAxACxB"
    };

    int total = 0;
    int a = 0;
    int b = 1;
    int c = 3;
    int d = 5;

    int length = input.length();

    for (int i = 0; i < length; i += 3) {
        char current[3]{input[i], input[i + 1], input[i + 2]};

        int creatureCount{0};
        if (current[0] != 'x') creatureCount++;
        if (current[1] != 'x') creatureCount++;
        if (current[2] != 'x') creatureCount++;

        if (creatureCount == 2) total += 2;
        if (creatureCount == 3) total += 6;

        switch (current[0]) {
            case 'B':
                total += b;
                break;
            case 'C':
                total += c;
                break;
            case 'D':
                total += d;
                break;
            default:
                total += a;
        }
        switch (current[1]) {
            case 'B':
                total += b;
                break;
            case 'C':
                total += c;
                break;
            case 'D':
                total += d;
                break;
            default:
                total += a;
        }
        switch (current[2]) {
            case 'B':
                total += b;
                break;
            case 'C':
                total += c;
                break;
            case 'D':
                total += d;
                break;
            default:
                total += a;
        }
    }
    return total;
}
